services:
  postgres:
    image: postgres:16
    container_name: project
    restart: unless-stopped
    environment:
      POSTGRES_DB: ClinicaSM
      POSTGRES_USER: Alejandro
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - axum_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axum_user -d axum_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  axum_network:
    driver: bridge
